
version: "3.3"

services:
  web:
    image: 0tchenash/docker:otche
    build: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - pg
  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5