name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: dockerbuild -t ${{ secrets.DOCKER_NAME}}/docker:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: login
        run: docker login -u ${{ secrets.DOCKER_NAME }} -p ${{ secrets.DOCKER_TOKEN }}
      -name: push
        run: docker push -t ${{ secrets.DOCKER_NAME }}/docker:$GITHUB_REF_NAME-$GITHUB_RUN_ID