name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: docker build -t ${{ secrets.DOCKER_NAME}}/docker:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: login
        run: docker login -u ${{ secrets.DOCKER_NAME }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: push
        run: docker push ${{ secrets.DOCKER_NAME }}/docker:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: render configs
        run: |
          mkdir deploy
          cat docker-compose.yml | envsubst > deploy/docker-compose.yml
          cat docker_config.py | envsubst > deploy/docker_config.py
      - name: copy files to server
        uses: appleboy/scp-action@master